name: base_django

services:
  db:
    image: mysql
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: boers
      MYSQL_PASSWORD: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_local

  adminer:
    image: adminer
    restart: always
    networks:
      - db_local
    ports:
      - 8080:8080

volumes:
  db_data:
networks:
  db_local:
